-- CreateTable
CREATE TABLE `set_jenis_tindakans` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `bidang_tindakan_id` BIGINT UNSIGNED NOT NULL,
    `created_at` TIMESTAMP(0) NULL,
    `updated_at` TIMESTAMP(0) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `set_tindakans` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `bidang_tindakan_id` BIGINT UNSIGNED NOT NULL,
    `jenis_tindakan_id` BIGINT UNSIGNED NULL,
    `name` VARCHAR(255) NOT NULL,
    `ada_parameter` VARCHAR(255) NOT NULL DEFAULT '0',
    `ada_hasilketerangan` VARCHAR(255) NOT NULL DEFAULT '0',
    `satuan_id` BIGINT UNSIGNED NULL,
    `tipe_hasil_id` BIGINT UNSIGNED NULL,
    `nilai_desimal` VARCHAR(255) NULL,
    `metoda_id` BIGINT UNSIGNED NULL,
    `acuan_metode` VARCHAR(255) NULL,
    `sample_id` BIGINT UNSIGNED NULL,
    `kategori_id` BIGINT UNSIGNED NOT NULL DEFAULT 46,
    `harga` VARCHAR(255) NOT NULL DEFAULT '0',
    `perkiraan_hari` TINYINT NULL,
    `hasil_pemeriksaan_id` BIGINT UNSIGNED NULL,
    `satuan_harga_id` BIGINT UNSIGNED NULL,
    `created_at` TIMESTAMP(0) NULL,
    `updated_at` TIMESTAMP(0) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_antrian_pasiens` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `no_antrian` INTEGER NOT NULL,
    `kode_pemeriksaan` VARCHAR(255) NULL,
    `pasien_id` BIGINT UNSIGNED NOT NULL,
    `tipe_pasien_id` BIGINT UNSIGNED NOT NULL,
    `rujukan_rs_id` BIGINT UNSIGNED NULL,
    `instansi_id` BIGINT UNSIGNED NULL,
    `dokter_id` BIGINT UNSIGNED NULL,
    `umur` INTEGER NULL,
    `waktu_kunjungan` DATE NOT NULL,
    `status_pendaftaran_id` BIGINT UNSIGNED NULL DEFAULT 29,
    `lab_validator_id` BIGINT UNSIGNED NULL DEFAULT 8,
    `validasi_kesmas` INTEGER NULL DEFAULT 0,
    `waktu_proses_pendaftaran` DATETIME(0) NULL,
    `user_proses_pendaftaran` BIGINT UNSIGNED NULL,
    `catatan` LONGTEXT NULL,
    `pembayaran_id` BIGINT UNSIGNED NULL,
    `status_pembayaran_id` BIGINT UNSIGNED NULL DEFAULT 31,
    `status_terima_sample_id` BIGINT UNSIGNED NULL DEFAULT 32,
    `sample_pengambil` VARCHAR(255) NULL,
    `sample_waktu` VARCHAR(255) NULL,
    `sample_jenis` VARCHAR(255) NULL,
    `sample_lokasi` VARCHAR(255) NULL,
    `sample_kondisi` VARCHAR(255) NULL,
    `sample_wadah` VARCHAR(255) NULL,
    `waktu_terima_sample` DATETIME(0) NULL,
    `user_terima_sample` BIGINT UNSIGNED NULL,
    `waktu_kirim_sample` DATETIME(0) NULL,
    `user_kirim_sample` BIGINT UNSIGNED NULL,
    `catatan_sample` LONGTEXT NULL,
    `status_pemeriksaan_id` BIGINT UNSIGNED NULL DEFAULT 34,
    `waktu_input_pemeriksaan` DATETIME(0) NULL,
    `user_input_pemeriksaan` BIGINT UNSIGNED NULL,
    `catatan_pemeriksaan` LONGTEXT NULL,
    `waktu_validasi` DATETIME(0) NULL,
    `user_validasi` BIGINT UNSIGNED NULL,
    `catatan_validasi` LONGTEXT NULL,
    `turn_around_time` VARCHAR(255) NULL,
    `deleted_at` TIMESTAMP(0) NULL,
    `created_at` TIMESTAMP(0) NULL,
    `updated_at` TIMESTAMP(0) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_user_customers` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `name_petugas` VARCHAR(255) NULL,
    `name_instansi` VARCHAR(255) NOT NULL,
    `instansi_mou_id` BIGINT UNSIGNED NULL,
    `is_instansi` BOOLEAN NOT NULL,
    `email` VARCHAR(255) NULL,
    `code_verification_email` INTEGER NULL,
    `code_verification_noPhone` INTEGER NULL,
    `status_verif_email` BOOLEAN NOT NULL DEFAULT false,
    `status_verif_noPhone` BOOLEAN NOT NULL DEFAULT false,
    `kode_pendaftaran` VARCHAR(255) NULL,
    `nik` VARCHAR(20) NULL,
    `type_account_id` BIGINT UNSIGNED NOT NULL DEFAULT 53,
    `jenis_kelamin_id` BIGINT UNSIGNED NULL,
    `golongan_darah_id` BIGINT UNSIGNED NULL,
    `tempat_lahir` VARCHAR(30) NULL,
    `tanggal_lahir` DATE NULL,
    `status_perkawinan_id` BIGINT UNSIGNED NULL,
    `pendidikan_id` BIGINT UNSIGNED NULL,
    `pekerjaan` VARCHAR(255) NULL,
    `alamat_domisili` LONGTEXT NULL,
    `agama` BIGINT UNSIGNED NULL,
    `provinsi_id` BIGINT UNSIGNED NULL,
    `kotaKabupaten_id` BIGINT UNSIGNED NULL,
    `kecamatan_id` BIGINT UNSIGNED NULL,
    `kelurahan_id` BIGINT UNSIGNED NULL,
    `kode_pos` VARCHAR(7) NULL,
    `warga_negara_id` BIGINT UNSIGNED NULL,
    `noHP` VARCHAR(15) NULL,
    `remember_token` VARCHAR(255) NULL,
    `created_at` TIMESTAMP(0) NULL,
    `updated_at` TIMESTAMP(0) NULL,

    INDEX `tbl_user_customers_golongan_darah_id_foreign`(`golongan_darah_id`),
    INDEX `tbl_user_customers_jenis_kelamin_id_foreign`(`jenis_kelamin_id`),
    INDEX `tbl_user_customers_kecamatan_id_foreign`(`kecamatan_id`),
    INDEX `tbl_user_customers_kelurahan_id_foreign`(`kelurahan_id`),
    INDEX `tbl_user_customers_kotakabupaten_id_foreign`(`kotaKabupaten_id`),
    INDEX `tbl_user_customers_pendidikan_id_foreign`(`pendidikan_id`),
    INDEX `tbl_user_customers_provinsi_id_foreign`(`provinsi_id`),
    INDEX `tbl_user_customers_status_perkawinan_id_foreign`(`status_perkawinan_id`),
    INDEX `tbl_user_customers_warga_negara_id_foreign`(`warga_negara_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
